pipeline:
  build:
    image: node:8.9.3
    commands:
      - npm install
      - npm run lint
      - npm run test
      - npm run build
    when:
      event: [ push, pull_request ]

  publish-service-docker-image:
    image: 258875347723.dkr.ecr.us-east-1.amazonaws.com/drone-plugin-docker-ecr
    repo: 258875347723.dkr.ecr.us-east-1.amazonaws.com/reddit-mobile
    registry: 258875347723.dkr.ecr.us-east-1.amazonaws.com
    dockerfile: Dockerfile.staging
    region: us-east-1
    tag: ${DRONE_BRANCH}
    when:
      event: [ push ]

  notify:
    image: 258875347723.dkr.ecr.us-east-1.amazonaws.com/drone-plugin-slack
    channel: mweb-salon
    secrets: [ slack_webhook ]
    when:
      status: [ success, failure ]
      event: [ pull_request ]
      branch: 2X

  create-github-deployment-for-push:
    image: 258875347723.dkr.ecr.us-east-1.amazonaws.com/drone-plugin-github-deployment
    repo: ${DRONE_REPO}
    ref: ${DRONE_BRANCH}
    deploy_env: staging
    auto_merge: false
    secrets:
      - github_integration_private_key_pem
      - github_app_integration_id
      - github_installation_id
    when:
      event: [ push ]

  add-github-comment:
    image: 258875347723.dkr.ecr.us-east-1.amazonaws.com/drone-plugin-github-comment
    repo: ${DRONE_REPO}
    canonical_repo: reddit/reddit-mobile
    issue_number: ${DRONE_PULL_REQUEST}
    comment: |
      ### ⏰ Branch is pending auto-deployment! ⏰
      - [Your branch](https://${DRONE_COMMIT_REFSPEC%%:2X}.mobile.dev.snooguts.net) will soon be available here 👉 https://${DRONE_COMMIT_REFSPEC%%:2X}.mobile.dev.snooguts.net
      - You can see all deployed branches [here](https://branches.mobile.dev.snooguts.net)
      - Your branch will be available once the CI build finishes
    secrets:
      - github_integration_private_key_pem
      - github_app_integration_id
      - github_installation_id
    when:
      event: [ pull_request ]

secrets:
  github_app_integration_id:
    driver: vault
    driver_opts:
      path: secret/drone/common/github_app_integration_id
  github_installation_id:
    driver: vault
    driver_opts:
      path: secret/drone/common/github_installation_id
  github_integration_private_key_pem:
    driver: vault
    driver_opts:
      path: secret/drone/common/github_integration_private_key_pem
  slack_webhook:
    driver: vault
    driver_opts:
      path: secret/drone/common/slack_webhook
